# src/core/steps/your_step_name.py

import asyncio
from playwright.async_api import async_playwright

async def run_step():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)

        context = await browser.new_context()

        # Anti detection
        await context.add_init_script("""
        Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
        Object.defineProperty(navigator, 'plugins', { get: () => [1,2,3] });
        Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
        Object.defineProperty(navigator, 'hardwareConcurrency', { get: () => 8 });
        """)

        page = await context.new_page()

        # --------------- PASTE FROM CODEGEN HERE ---------------
        # This part is auto-generated by: playwright codegen
        # -------------------------------------------------------

        await browser.close()

if __name__ == "__main__":
    asyncio.run(run_step())
