research_news:
  description: >
    YOU MUST USE THE DUCKDUCKGO SEARCH TOOL TO FIND CURRENT NEWS. DO NOT use your internal knowledge.
    
    Search and collect the 10 MOST RELEVANT and RECENT news articles about {topic}.
    
    MANDATORY STEPS - DO EXACTLY 3 SEARCHES, NO MORE:
    
    Search 1: "{topic} news"
    Search 2: "{topic} latest"  
    Search 3: "{topic} 2025"
    
    STOP AFTER 3 SEARCHES. Do not search again even if results seem poor.
    
    IMPORTANT:
    - Keep queries SHORT (2-3 words maximum)
    - Do NOT use quotes, operators, or words like "today", "breaking"
    - Do exactly 3 searches and STOP
    - Work with whatever results you get from those 3 searches
    - Extract the best 10 news items from the combined results
    
    If some results are not crypto-related (like Microsoft or real estate),
    just ignore those and focus on the crypto-related results you did find.
    
    CRITICAL REQUIREMENTS:
    - Perform EXACTLY 3 web searches, no more, no less
    - Only include news from 2024-2025 in your final output
    - If you can't find 10 perfect items, include the best ones you found
    
    FOR EACH NEWS ITEM COLLECT:
    - Headline/Title
    - Brief summary (2-3 sentences max)
    - Source
    - Why it's relevant/interesting
    - Viral potential (why people would care)
  
  expected_output: >
    A JSON file containing exactly 10 news items with this structure:
    {
      "topic": "the search topic",
      "search_date": "2025-10-20",
      "news": [
        {
          "title": "News headline",
          "summary": "Brief 2-3 sentence summary",
          "source": "Source name or URL",
          "date": "Publication date (MUST be from 2024 or 2025)",
          "relevance": "Why this is important/interesting",
          "viral_potential": "Why people would care about this"
        }
      ]
    }
    
    VALIDATION REQUIREMENTS:
    - ALL news items MUST be from 2024 or 2025
    - If you cannot find recent news, you MUST use the search tool again
    - DO NOT include news from 2023 or earlier under any circumstances
    - Each news item MUST include a date field showing when it was published
  
  agent: news_hunter
  output_file: output/news_collection.json

create_viral_script:
  description: >
    Analyze the 10 news items and CREATE ONE VIRAL YOUTUBE SHORTS SCRIPT.
    
    STEP 1 - ANALYSIS:
    Review all 10 news items and identify which one (or combination) has the BEST potential
    for creating engaging, evergreen-style content that can go viral.
    
    Consider:
    - Which story has the most curiosity hook?
    - Which can be explained clearly in 60 seconds?
    - Which has educational value that remains relevant?
    - Which will make people watch until the end?
    
    STEP 2 - SCRIPT CREATION (Faceless YouTube Shorts Style):
    
    Write a 60-second script following these proven retention strategies:
    
    HOOK (0-3 seconds):
    - Open with a bold statement, shocking fact, or intriguing question
    - Make it impossible to scroll away
    - Examples: "This just changed everything in crypto..." / "You're doing this wrong..." / "Nobody is talking about this but..."
    
    PATTERN INTERRUPTS (throughout):
    - Use short, punchy sentences
    - Vary sentence length for rhythm
    - Include "But here's the thing..." / "And this is crazy..." / "Wait, it gets better..."
    - Build curiosity loops that pay off
    
    RETENTION TACTICS:
    - Tease valuable information: "And the third reason will surprise you..."
    - Use the word "YOU" frequently to make it personal
    - Create mini-cliffhangers: "But before I tell you that..."
    - Build to a satisfying conclusion
    
    ENDING:
    - Quick recap of key value delivered
    - Strong call-to-action (like, subscribe, comment)
    - Can include "Crypto Clarity" name naturally if it fits
    
    VOICE/TONE FOR AI NARRATION:
    - Conversational but authoritative
    - Energetic without being shouty
    - Clear pronunciation for technical terms
    - Natural pauses for emphasis
    
    STEP 3 - TECHNICAL SPECIFICATIONS:
    Define the exact voice characteristics, music style, and emotional tone
    needed for ElevenLabs audio generation.
  
  expected_output: >
    A JSON file with this EXACT structure for ElevenLabs production:
    {
      "video_title": "Catchy, clear title optimized for YouTube Shorts",
      "script": "The complete script text, clean and ready for voice generation. No timestamps, no image references, just the pure narrative text that will be spoken.",
      "voice_specifications": {
        "tone": "e.g., Confident and engaging",
        "pace": "e.g., Moderate with strategic pauses",
        "energy_level": "e.g., High energy but controlled",
        "style": "e.g., Educational storyteller",
        "emotional_direction": "Specific guidance like 'Start intrigued, build excitement, end authoritative'"
      },
      "music_suggestion": {
        "genre": "e.g., Upbeat electronic",
        "mood": "e.g., Modern and professional",
        "intensity": "e.g., Medium - shouldn't overpower voice",
        "style_reference": "e.g., Similar to tech review channels"
      },
      "engagement_notes": "Brief notes on what makes this script work for retention",
      "estimated_duration": "58 seconds"
    }
  
  agent: script_creator
  context:
    - research_news
  output_file: output/video_script.json